"""add issue_date to documents

Revision ID: fd8fec1f9824
Revises: a3f8b2c4d5e6
Create Date: 2026-01-31 15:30:54.356640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8fec1f9824'
down_revision: Union[str, Sequence[str], None] = 'a3f8b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_documents_issue_date'), 'documents', ['issue_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_issue_date'), table_name='documents')
    op.drop_column('documents', 'issue_date')
    # ### end Alembic commands ###
